---
- name: COUCHDB_START | Deploy CouchDB cluster
  hosts: manager
  become: yes
  vars:
    ansible_folder_dir: "../.."

  tasks:
    - name: Ensure cluster directory exists
      file:
        path: /home/{{ ansible_user }}/couchdb-config
        state: directory
        mode: '0750'

    - name: Copy stack file
      copy:
        src: "{{ ansible_folder_dir }}/config/couchdb/stack.yml"
        dest: /home/{{ ansible_user }}/couchdb-config/stack.yml

    - name: Copy .env file
      copy:
        src: "{{ ansible_folder_dir }}/config/couchdb/.env"
        dest: /home/{{ ansible_user }}/couchdb-config/.env

    - name: Deploy stack
      shell: |
        set -a && . ./.env && set +a && \
        docker stack deploy -c stack.yml vss-couch
      # change dir to force docker to load the .env file from there
      args:
        chdir: /home/{{ ansible_user }}/couchdb-config

- name: COUCHDB_START | Test Docker Swarm CouchDB cluster
  hosts: manager
  become: yes
  vars:
    num_swarm_services: 2
  tasks:
    - name: Check if all services are running
      shell: docker service ls --filter label=com.docker.stack.namespace=vss-couch --format '{{ "{{.Name}} {{.Replicas}}" }}'
      register: services_status
      until: services_status.stdout_lines | select("search", "1/1") | list | length == num_swarm_services
      retries: 10
      delay: 10

    - name: Get placement of couchdb_node_01 
      shell: docker service ps vss-couch_couchdb_node_01 --format '{{ "{{.Name}} {{.Node}} {{.CurrentState}}" }}'
      register: couchdb_node_01_ps

    - name: Get placement of couchdb_node_02
      shell: docker service ps vss-couch_couchdb_node_02 --format '{{ "{{.Name}} {{.Node}} {{.CurrentState}}" }}'
      register: couchdb_node_02_ps

    - name: Print container placement
      debug:
        msg: |
          CouchDB Node 1: {{ couchdb_node_01_ps.stdout }}
          CouchDB Node 2: {{ couchdb_node_02_ps.stdout }}

- name: COUCHDB_START | Clean any sensitive files
  hosts: manager
  become: yes
  tasks:
    - name: Remove .env file
      file:
        path: /home/{{ ansible_user }}/couchdb-config/.env
        state: absent
