---
- name: COUCHDB_CONFIGURE | Configure CouchDB cluster with async replication
  hosts: manager
  become: yes
  vars:
    infra_folder_dir: "../../.."
    ansible_folder_dir: "../.."
  
  tasks:
    - name: Ensure cluster directory exists
      file:
        path: /home/{{ ansible_user }}/couchdb-config
        state: directory
        mode: 0755

    - name: Copy script
      copy:
        src: "{{ ansible_folder_dir }}/config/couchdb/init-cluster-async.sh"
        dest: /home/{{ ansible_user }}/couchdb-config/init-cluster-async.sh
        mode: 0755
    
    - name: Copy .env file
      copy:
        src: "{{ ansible_folder_dir }}/config/couchdb/.env"
        dest: /home/{{ ansible_user }}/couchdb-config/.env
        mode: 0755

    - name: Copy hosts file
      copy:
        src: "{{ infra_folder_dir }}/tmp/hosts"
        dest: /home/{{ ansible_user }}/couchdb-config/hosts
        mode: 0755

    - name: Run CouchDB script
      shell: ./init-cluster-async.sh
      args:
        chdir: /home/{{ ansible_user }}/couchdb-config
      register: script_output
      ignore_errors: true  # see output even on error

    - name: Show replication script output
      debug:
        var: script_output.stdout_lines

