version: '3.8'

services:
  scylla-node1:
    image: scylladb/scylla:5.2.0
    container_name: scylla-node1
    command: --seeds=scylla-node1,scylla-node2 --smp 1 --memory 750M --overprovisioned 1 --api-address 0.0.0.0 --reactor-backend=epoll
    ports:
      - "10030:9042"
    #volumes:
    #  - "./config/scylla.yaml:/etc/scylla/scylla.yaml"
    #  - "./config/cassandra-rackdc.properties.dc1:/etc/scylla/cassandra-rackdc.properties"
    #  - "./config/mutant-data.txt:/mutant-data.txt"
    networks:
      - scylla-net
    deploy:
      placement:
        constraints:
          - node.hostname == node-us

  scylla-node2:
    image: scylladb/scylla:5.2.0
    container_name: scylla-node2
    command: --seeds=scylla-node1,scylla-node2 --smp 1 --memory 750M --overprovisioned 1 --api-address 0.0.0.0 --reactor-backend=epoll
    ports:
      - "10031:9042"
    #volumes:
    #  - "./config/scylla.yaml:/etc/scylla/scylla.yaml"
    #  - "./config/cassandra-rackdc.properties.dc1:/etc/scylla/cassandra-rackdc.properties"
    networks:
      - scylla-net
    deploy:
      placement:
        constraints:
          - node.hostname == node-us

  scylla-node3:
    image: scylladb/scylla:5.2.0
    container_name: scylla-node3
    command: --seeds=scylla-node1,scylla-node2 --smp 1 --memory 750M --overprovisioned 1 --api-address 0.0.0.0 --reactor-backend=epoll
    ports:
      - "10032:9042"
    #volumes:
    #  - "./config/scylla.yaml:/etc/scylla/scylla.yaml"
    #  - "./config/cassandra-rackdc.properties.dc1:/etc/scylla/cassandra-rackdc.properties"
    networks:
      - scylla-net
    deploy:
      placement:
        constraints:
          - node.hostname == node-us

  scylla-node4:
    image: scylladb/scylla:5.2.0
    container_name: scylla-node4
    command: --seeds=scylla-node1,scylla-node4 --smp 1 --memory 750M --overprovisioned 1 --api-address 0.0.0.0 --reactor-backend=epoll
    ports:
      - "10033:9042"
    #volumes:
    #  - "./config/scylla.yaml:/etc/scylla/scylla.yaml"
    #  - "./config/cassandra-rackdc.properties.dc2:/etc/scylla/cassandra-rackdc.properties"
    networks:
      - scylla-net
    deploy:
      placement:
        constraints:
          - node.hostname == node-ap

  scylla-node5:
    image: scylladb/scylla:5.2.0
    container_name: scylla-node5
    command: --seeds=scylla-node1,scylla-node4 --smp 1 --memory 750M --overprovisioned 1 --api-address 0.0.0.0 --reactor-backend=epoll
    ports:
      - "10034:9042"
    #volumes:
    #  - "./config/scylla.yaml:/etc/scylla/scylla.yaml"
    #  - "./config/cassandra-rackdc.properties.dc2:/etc/scylla/cassandra-rackdc.properties"
    networks:
      - scylla-net
    deploy:
      placement:
        constraints:
          - node.hostname == node-ap

  scylla-node6:
    image: scylladb/scylla:5.2.0
    container_name: scylla-node6
    command: --seeds=scylla-node1,scylla-node4 --smp 1 --memory 750M --overprovisioned 1 --api-address 0.0.0.0 --reactor-backend=epoll
    ports:
      - "10035:9042"
    #volumes:
    #  - "./config/scylla.yaml:/etc/scylla/scylla.yaml"
    #  - "./config/cassandra-rackdc.properties.dc2:/etc/scylla/cassandra-rackdc.properties"
    networks:
      - scylla-net
    deploy:
      placement:
        constraints:
          - node.hostname == node-ap

networks:
  scylla-net:
    driver: overlay
