---
- name: CLUSTER_PROVISION | Deploy dsb mediamicroservices
  hosts: swarm_nodes
  become: yes

  tasks:
    - name: Install system packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - chrony
          - at
        state: present
        update_cache: yes

    - name: Ensure chrony is enabled and running
      service:
        name: chrony
        state: started
        enabled: yes

    - name: Force NTP time sync
      shell: chronyc -a makestep
      register: ntp_sync_result
      changed_when: false

    - name: Wait 5 seconds to allow time sync
      wait_for:
        timeout: 5

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present
        filename: docker

    - name: Install Docker and Docker Compose
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose
        state: latest
        update_cache: yes
        
    - name: Wait until Docker is responding
      shell: docker info
      register: docker_ready
      retries: 10
      delay: 5
      until: docker_ready.rc == 0

    - name: Add {{ ansible_user }} user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Install postgresql client to test connectivity to database
      apt:
        name:
          - postgresql-client
        state: latest
        update_cache: yes

    #- name: Import scylladb gpg key
    #  shell: >
    #    gpg --homedir /tmp --no-default-keyring
    #    --keyring /etc/apt/keyrings/scylladb.gpg
    #    --keyserver hkp://keyserver.ubuntu.com:80
    #    --recv-keys a43e06657bac99e3
    #  args:
    #    creates: /etc/apt/keyrings/scylladb.gpg
#
    #- name: Install scylladb apt source
    #  get_url:
    #    url: http://downloads.scylladb.com/deb/debian/scylla-2025.2.list
    #    dest: /etc/apt/sources.list.d/scylla.list
    #    mode: "0644"
#
    #- name: Install scylladb package
    #  apt:
    #    name: scylla
    #    state: present
    #    update_cache: yes
