---
- name: APP_DEPLOY | Deploy dsb mediamicroservices
  hosts: dsb_mediamicroservices
  become: yes
  vars:
    infra_folder_dir: "../../.."
    local_app_folder_dir: "../../../../DeathStarBench/mediaMicroservices"
    remote_app_folder_dir: "/home/{{ ansible_user }}/dsb-mediamicroservices"

  tasks:
    - name: Copy nginx web server files for docker-compose
      copy:
        src: "{{ local_app_folder_dir }}/nginx-web-server/"
        dest: "{{ remote_app_folder_dir }}/nginx-web-server/"
        mode: 0755
    
    - name: Copy gen lua files for docker-compose
      copy:
        src: "{{ local_app_folder_dir }}/gen-lua/"
        dest: "{{ remote_app_folder_dir }}/gen-lua/"
        mode: 0755

- name: APP_DEPLOY | Copy .env file to us instance
  hosts: node_us
  become: yes
  vars:
    infra_folder_dir: "../../.."
    remote_app_folder_dir: "/home/{{ ansible_user }}/dsb-mediamicroservices"

  tasks:
    - name: Copy .env file to us instance
      copy:
        src: "{{ infra_folder_dir }}/providers/aws/us.env"
        dest: "{{ remote_app_folder_dir }}/.env"
        mode: 0755
    
    - name: Append line with couchdb address ({{ ansible_host }}:10010) to .env at US
      lineinfile:
        path: "{{ remote_app_folder_dir }}/.env"
        line: "COUCHDB_ADDRESS={{ ansible_host }}:10010"
        create: yes
        state: present

    - name: Append line with postgresql address ({{ ansible_host }}:10020) to .env at US
      lineinfile:
        path: "{{ remote_app_folder_dir }}/.env"
        line: "POSTGRESQL_ADDRESS={{ ansible_host }}:10020"
        create: yes
        state: present

    - name: Append line with scylladb address ({{ ansible_host }}:10030) to .env at US
      lineinfile:
        path: "{{ remote_app_folder_dir }}/.env"
        line: "SCYLLADB_ADDRESS={{ ansible_host }}:10030"
        create: yes
        state: present

- name: APP_DEPLOY | Copy .env file to ap instance
  hosts: node_ap
  become: yes
  vars:
    infra_folder_dir: "../../.."
    remote_app_folder_dir: "/home/{{ ansible_user }}/dsb-mediamicroservices"

  tasks:
    - name: Copy .env file to us instance
      copy:
        src: "{{ infra_folder_dir }}/providers/aws/ap.env"
        dest: "{{ remote_app_folder_dir }}/.env"
        mode: 0755

    - name: Append line with couchdb address ({{ ansible_host }}:10011) to .env at AP
      lineinfile:
        path: "{{ remote_app_folder_dir }}/.env"
        line: "COUCHDB_ADDRESS={{ ansible_host }}:10011"
        create: yes
        state: present

    - name: Append line with postgresql address ({{ ansible_host }}:10022) to .env at AP
      lineinfile:
        path: "{{ remote_app_folder_dir }}/.env"
        line: "POSTGRESQL_ADDRESS={{ ansible_host }}:10022"
        create: yes
        state: present

    - name: Append line with scylladb address ({{ ansible_host }}:10033) to .env at AP
      lineinfile:
        path: "{{ remote_app_folder_dir }}/.env"
        line: "SCYLLADB_ADDRESS={{ ansible_host }}:10033"
        create: yes
        state: present
