---
- name: Deploy dsb mediamicroservices
  hosts: dsb_mediamicroservices
  become: yes
  vars:
    infra_folder_dir: "../.."
    local_app_folder_dir: "../../../DeathStarBench/mediaMicroservices"
    remote_app_folder_dir: "/home/{{ ansible_user }}/dsb-mediamicroservices"

  tasks:
    - name: Copy nginx web server files for docker-compose
      copy:
        src: "{{ local_app_folder_dir }}/nginx-web-server/"
        dest: "{{ remote_app_folder_dir }}/nginx-web-server/"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0755
    
    - name: Copy gen lua files for docker-compose
      copy:
        src: "{{ local_app_folder_dir }}/gen-lua/"
        dest: "{{ remote_app_folder_dir }}/gen-lua/"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0755

- name: Copy .env file to us instance
  hosts: node_us
  become: yes
  vars:
    infra_folder_dir: "../.."
    remote_app_folder_dir: "/home/{{ ansible_user }}/dsb-mediamicroservices"

  tasks:
    - name: Copy .env file to us instance
      copy:
        src: "{{ infra_folder_dir }}/env/us.env"
        dest: "{{ remote_app_folder_dir }}/.env"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0755
    
    - name: Append line with couchdb address to .env
      lineinfile:
        path: "{{ remote_app_folder_dir }}/.env"
        line: "COUCHDB_ADDRESS={{ ansible_host }}:10010"
        create: yes
        state: present

- name: Copy .env file to ap instance
  hosts: node_ap
  become: yes
  vars:
    infra_folder_dir: "../.."
    remote_app_folder_dir: "/home/{{ ansible_user }}/dsb-mediamicroservices"

  tasks:
    - name: Copy .env file to us instance
      copy:
        src: "{{ infra_folder_dir }}/env/ap.env"
        dest: "{{ remote_app_folder_dir }}/.env"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0755

    - name: Append line with couchdb address to .env
      lineinfile:
        path: "{{ remote_app_folder_dir }}/.env"
        line: "COUCHDB_ADDRESS={{ ansible_host }}:10011"
        create: yes
        state: present
