---
- name: Start microservices with docker compose
  hosts: dsb_mediamicroservices
  become: yes
  vars:
    local_app_base_dir: "../../../DeathStarBench/mediaMicroservices"
    remote_app_base_dir: "/home/ubuntu/dsb-mediamicroservices"

  tasks:
    - name: Copy docker compose file
      copy:
        src: "{{ local_app_base_dir }}/docker-compose.yml"
        dest: "{{ remote_app_base_dir }}/docker-compose.yml"
        owner: ubuntu
        group: ubuntu
        mode: 0755
    
    - name: Run docker compose pull
      shell: docker-compose pull
      args:
        chdir: "{{ remote_app_base_dir }}"
        
    - name: Run docker compose up
      shell: docker-compose up -d
      args:
        chdir: "{{ remote_app_base_dir }}"
