---
- name: Start microservices with docker compose
  hosts: dsb_mediamicroservices
  become: yes
  vars:
    remote_app_folder_dir: "/home/{{ ansible_user }}/dsb-mediamicroservices"
    local_app_folder_dir: "../../../DeathStarBench/mediaMicroservices"

  tasks:
    - name: Copy docker compose file
      copy:
        src: "{{ local_app_folder_dir }}/docker-compose.yml"
        dest: "{{ remote_app_folder_dir }}/docker-compose.yml"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0755
    
    - name: Run docker compose pull
      shell: docker-compose pull
      args:
        chdir: "{{ remote_app_folder_dir }}"
        
    - name: Run docker compose up
      shell: docker-compose up -d
      args:
        chdir: "{{ remote_app_folder_dir }}"
