---
- name: Configure PostgreSQL cluster
  hosts: manager
  become: yes
  vars:
    infra_folder_dir: "../.."
    ansible_folder_dir: ".."
  
  tasks:
    - name: Ensure cluster directory exists
      file:
        path: /home/{{ ansible_user }}/postgresql-config
        state: directory
        mode: 0755

    - name: Copy async script
      copy:
        src: "{{ ansible_folder_dir }}/config/postgresql/init-postgresql.sh"
        dest: /home/{{ ansible_user }}/postgresql-config/init-postgresql.sh
        mode: 0755
    
    - name: Copy .env file
      copy:
        src: "{{ ansible_folder_dir }}/config/postgresql/.env"
        dest: /home/{{ ansible_user }}/postgresql-config/.env
        mode: 0755

    - name: Copy hosts file
      copy:
        src: "{{ infra_folder_dir }}/tmp/hosts"
        dest: /home/{{ ansible_user }}/postgresql-config/hosts
        mode: 0755

    - name: Run postgresql script
      shell: ./init-postgresql.sh
      args:
        chdir: /home/{{ ansible_user }}/postgresql-config
      register: script_output
      ignore_errors: true  # see output even on error

    - name: Show replication script output
      debug:
        var: script_output.stdout_lines

